<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']					= 'Danh mục';
$lang['error_must_select']			= 'Cần chọn một danh mục để tổ chức';
$lang['error_not_found']			= 'Không tìm thấy danh mục yêu cầu';
$lang['organize_category']			= 'Tổ chức "%s" Danh mục';
$lang['organize']					= 'Tổ chức';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Danh mục';
$lang['name']						= 'Tên';
$lang['slug']						= 'Slug';
$lang['description']				= 'Nội dung';
$lang['excerpt']					= 'Trích dẫn';
$lang['sequence']					= 'Trình tự';
$lang['image']						= 'Hình ảnh';
$lang['seo_title']					= 'SEO Title';
$lang['meta']						= 'Meta Data';
$lang['message_category_saved']		= 'Danh mục đã được lưu';
$lang['error_file_upload']			= '<p>Không file nào được chọn để tải lên.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'Danh mục đã xóa';
$lang['current_file']				= 'File hiện tại';
$lang['confirm_delete_category']	= 'Bạn có muốn xóa danh mục này không?';
$lang['add_new_category']			= 'Thêm mới danh mục';
$lang['top_level_category']         = 'Danh mục cao nhất';
$lang['no_categories']				= 'Không có danh mục nào';
$lang['attributes']					= 'Thuộc tính';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Cha';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= 'Kéo thả sản phẩm để sắp xếp.';
$lang['sku']						= 'SKU';
$lang['price']						= 'Giá';
$lang['sale']						= 'Hạ giá';
$lang['max_file_size']				= 'Dung lượng file tối đa';

$lang['en_name']					= 'Tên tiếng anh';
$lang['en_description']				= 'Nội dung tiếng anh';
$lang['en_excerpt']					= 'Trích dẫn tiếng anh';